server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  profiles:
    include:
      - oauth
      - redis
jwt:
  live:
    access: 1800000
    refresh: 1800000
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK